apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-service
  labels:
    app: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
      name: port0
    - protocol: TCP
      port: 4443
      targetPort: 4443
      name: port1
    - protocol: TCP
      port: 4442
      targetPort: 4442
      name: port2
  type: LoadBalancer